### ISSUE TITLE
Static, Dynamic, Hybrid

### ISSUE THREAD

**Issue by nicosammito** [code0-tech/aquila#96]
### General

We need to differentiate between `Update Flow` and `Compile Target` for every version.
The Update Flow is the way the flows are updated (LIVE, RELEASE, FILES). The Compile Target can either be INTERPRETED or COMPILED, which changes the infrastructure drastically.

Also the dynamic and the hybrid variant can also connect to our cloud IDE from self hosted executions.

### Dynamic

The dynamic version of Aquila is similar to a dev version, where every update is directly committed to the local flow store. Thus makes sure that every change in the IDE can be checked and worked with instantly.

Update Flow: LIVE
Compile Target: INTERPRETED

### Hybrid

The hybrid solution is a mix of the static and dynamic version. A update is only triggered on release and not on every change. The hybrid solution is also the only version that is capable of changing between the dynamic or the static setup. 

Update Flow: RELEASE
Compile Target: INTERPRETED or COMPILED

### Static
The static version is a standalone build of the execution and does not have any connection to the IDE. The flows are stored as json and no update can be emitted. It will use the Rust Builder to compile the adapter and Taurus.

Update Flow: FILES
Compile Target: COMPILED

**Comment by raphael-goetz** [comment]
In every setup, Sagittarius acts as the server, while Aquila always functions as the client. The configuration determining whether Aquila operates in a static, dynamic, or hybrid mode is not controlled by a single configuration variable.

Currently, Aquila can be configured as follows:

- Hybrid: Aquila starts with a scheduler that requests new releases from Sagittarius.
- Dynamic: Aquila starts with a gRPC stream to receive live updates.
- Static: If both the scheduler (1) and gRPC stream (2) are disabled, Aquila initializes from a file.

If you prefer, I can modify the configuration approach so that instead of setting individual options to true or false, you can directly specify the mode (static, dynamic, or hybrid) and then configure the necessary variables accordingly.

**Comment by nicosammito** [comment]
> In every setup, Sagittarius acts as the server, while Aquila always functions as the client. The configuration determining whether Aquila operates in a static, dynamic, or hybrid mode is not controlled by a single configuration variable.
> 
> Currently, Aquila can be configured as follows:
> 
> * Hybrid: Aquila starts with a scheduler that requests new releases from Sagittarius.
> * Dynamic: Aquila starts with a gRPC stream to receive live updates.
> * Static: If both the scheduler (1) and gRPC stream (2) are disabled, Aquila initializes from a file.
> 
> If you prefer, I can modify the configuration approach so that instead of setting individual options to true or false, you can directly specify the mode (static, dynamic, or hybrid) and then configure the necessary variables accordingly.

We should rethink the way how aquila gets updates in hybrid mode. Maybe its a better option that sagittarius calls aquila with a update here.

**Comment by raphael-goetz** [comment]
Well then Aquila needs to tell Sagittarius that it should be updated by releases. Currently Aquila is just the client and Sagittarius the server, it would be nice to keep it that way. But @Taucher2003 what do you think???
